export const BLACK = "#212121"
export const WHITE = "#F7F7F7"
export const LIGHT_GRAY = "#E0E0E0"
export const GRAY = "#BDBDBD"
export const DARK_GRAY = "#757575"
export const CERISE_STRONG = "#EE2A7B"
export const CERISE_NEW = "#E83D84"
export const CERISE_LIGHT = "#EC5F99"
